# Generated by Django 5.0.6 on 2024-06-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_alter_autor_retrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='retrato',
            field=models.ImageField(blank=True, null=True, upload_to='biblioteca_imagens/'),
        ),
    ]
