# Generated by Django 4.0.6 on 2024-04-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='diretor',
        ),
        migrations.AddField(
            model_name='filme',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='filme_images/'),
        ),
    ]
