# Generated by Django 5.0.4 on 2024-05-06 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='curricularIUnitReadableCode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.disciplina'),
        ),
    ]
