# Generated by Django 5.0.4 on 2024-04-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='nacionality',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
