# Generated by Django 5.0.4 on 2024-04-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0002_band_nacionality'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
