# Generated by Django 5.0.6 on 2024-06-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0003_song_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='letra',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
