# Generated by Django 5.0.6 on 2024-06-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0004_song_letra'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='biografia',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
